### PR TITLE
added TRIPS-WXDAI Pool

### PR DESCRIPTION
**Pull request by lucadgtrip**

### CODE REVIEW

**Comment by onbjerg** [comment]
Hi, I have some questions

- What is TRIPS?
- Is there are funding proposal up for TRIPS?
- Is it the aforementioned proposal likely to pass?

Thanks :blush:

**Comment by lucadgtrip** [comment]
Hi!
Trips is a set of open booking protocols for the rentals industry (Airbnb and others) which will evolve in a fully fledged booking platform.
We are partners with https://github.com/OriginProtocol and our development is based on their marketplaces protocols.

There's no funding proposal yet, as we're educating the community about xDAI and 1Hive.

> Is it the aforementioned proposal likely to pass?

We'll ask a proportionate amount, so I think so.

Thanks!

**Comment by onbjerg** [comment]
Sorry for the delayed response!

I'd wait with merging this until a proposal is up or close to passing. We should probably have guidelines around this, but I think naming a pool will create a sense that it has been "legitimised" which I only think we should do if the pool is actually funded.

Historically the community has not been keen on funding pools for tokens that are super new. I'm still unsure how I would even get TRIPS to pool liquidity and attain farming rewards, which would probably also be a deal-breaker.

There's been some talk of being able to configure rewards to be in other tokens than Honey, which would probably change this outlook.

Let me know if you have different opinions on that :)

**Comment by lucadgtrip** [comment]
It makes total sense. 
Rewards in Trips would be amazing to have.

**Comment by fbgoat** [comment]
Closing this PR, since TRIPS-WXDAI pools isn't mention in any proposal yet.

**Pull request closed without merging**
